<Project Sdk="Microsoft.NET.Sdk.Web">  
<!-- sdk entry =>defines what is the type of application -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <!-- target framework defines the set of apis available to the application -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Dtos\" />
  </ItemGroup>

</Project>
